app/currency_app/urls.py
from django.urls import path
from .views import (hello_world,
                    filter_contact_us_msg,
                    rate_list,
                    SourceListView,
                    SourceCreateView,
                    SourceUpdateView,
                    SourceDeleteView,
                    SourceDetailView,
                    ContactUsCreateView,
                    rate_create,
                    rate_update,
                    rate_delete,
                    rate_details)


urlpatterns = [
    path('', hello_world, name='hello_world'),
    path('show_msgs/', filter_contact_us_msg, name='filter_messages'),
    path('rate_list/', rate_list, name='rate_list'),
    path('rate_list/rate_create/', rate_create, name='rate_create'),
    path('rate_list/rate_update/<int:rate_id>/',
         rate_update, name='rate_update'),
    path('rate_list/rate_delete/<int:rate_id>/',
         rate_delete, name='rate_delete'),
    path('rate_list/rate_details/<int:rate_id>/',
         rate_details, name='rate_details'),
    path('source_list/', SourceListView.as_view(), name='source_list'),
    path('source_list/source_create/',
         SourceCreateView.as_view(), name='source_create'),
    path('source_list/source_delete/<int:pk>/',
         SourceDeleteView.as_view(), name='source_delete'),
    path('source_list/source_update/<int:pk>/',
         SourceUpdateView.as_view(), name='source_update'),
    path('source_list/source_details/<int:pk>/',
         SourceDetailView.as_view(), name='source_details'),
    path('contact_us_form/', ContactUsCreateView.as_view(),
         name='contact_us_form')

]

app/settings/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('currency_app.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    url(r'^silk/', include('silk.urls', namespace='silk'))
]

app/currency_app/models.py
from django.db import models
from currency_app import modelchoices as mch


class Source(models.Model):

    id = models.IntegerField(primary_key=True) # noqa
    name = models.CharField(max_length=64, unique=True)
    source_url = models.CharField(max_length=255, default="")

    def __str__(self):
        return self.name


class Rate(models.Model):

    sale = models.DecimalField(max_digits=5, decimal_places=2)
    buy = models.DecimalField(max_digits=5, decimal_places=2)
    source = models.ForeignKey(Source, to_field='name',
                               on_delete=models.CASCADE)
    currency = models.CharField(max_length=3, choices=mch.RATE_CHOICES)
# Use rate.get_currency_diplay in template
# to display 'human' values from choices
# get_{attribute_name}_display - is the format
    created = models.DateTimeField(auto_now_add=True)


class ContactUs(models.Model):

    id = models.IntegerField(primary_key=True) # noqa
    email_from = models.CharField(max_length=24)
    subject = models.CharField(max_length=50)
    message = models.CharField(max_length=500)
    created = models.DateTimeField(auto_now_add=True)


class ResponseLog(models.Model):

    created = models.DateTimeField(auto_now_add=True)
    status_code = models.PositiveIntegerField()
    path = models.CharField(max_length=255)
    response_time = models.PositiveIntegerField(help_text='In milliseconds') # noqa
    request_methods = models.CharField(max_length=10,
                                       choices=mch.REQUEST_METHODS,
                                       default='GET')

app/currency_app/forms.py
from django import forms
from .models import ContactUs, Rate, Source


class SourceForm(forms.ModelForm):

    class Meta:

        model = Source
        fields = ('name', 'source_url')

    def get_data(self):
        return Source.objects.all()

    def clean(self):
        cleaned_data = super().clean()
        all_sources = self.get_data()
        name_cleaned = cleaned_data['name']
        # source_url_cleaned = cleaned_data['source_url']

        if all_sources.filter(name=name_cleaned).exists():
            self.add_error(None, ValueError('Name already exists!'))
        elif all_sources.filter(name=name_cleaned).exists():
            self.add_error(None, ValueError('Url already exists!'))


class RateForm(forms.ModelForm):

    class Meta:

        model = Rate
        fields = ('sale', 'buy', 'source', 'currency')


class ContactUsForm(forms.ModelForm):

    class Meta:

        model = ContactUs
        fields = ('email_from', 'subject', 'message')

app/currency_app/views.py
from django.urls import reverse_lazy

from .models import Rate, ContactUs, Source

from django.core.mail import send_mail

from django.conf import settings

from django.views.generic import (CreateView,
                                  UpdateView,
                                  DeleteView,
                                  DetailView,
                                  ListView)
from django.shortcuts import render, redirect, get_object_or_404
from currency_app.forms import SourceForm, RateForm, ContactUsForm


# Create your views here.
from django.http import HttpResponse


class ResponseTimeMixin:

    def rate_dispatch(self, request, *args, **kwargs):
        import time
        start_time = time.time()
        print('RATE LIST DISPATCH') # noqa
        response = super().dispatch(request, *args, **kwargs)
        end_time = time.time()
        time_taken = start_time - end_time
        print(f'Response time: {time_taken} seconds') # noqa
        return response


def hello_world(request):
    return HttpResponse('Hello World!')


def rate_list(request):
    rates = Rate.objects.all().order_by('-created')
    return render(request, 'rate_page.html', {'rates': rates, })


def filter_contact_us_msg(request):
    msgs_filtered = ContactUs.objects.all()

    return render(request,
                  'contact_details.html',
                  {'msgs_filtered': msgs_filtered})


def contact_us_form(request):

    if request.method == 'POST':
        contact_request = ContactUsForm(request.POST)
        if contact_request.is_valid():
            contact_request.save()
            return redirect('filter_messages')

        else:
            return redirect('filter_messages')


def show_sources(request):
    sources = Source.objects.all()
    return render(request,
                  'show_sources.html',
                  {'sources': sources})


def rate_create(request):
    if request.method == 'POST':
        create_form = RateForm(request.POST)
        if create_form.is_valid():
            create_form.save()
            return redirect('rate_list')
    elif request.method == 'GET':
        create_form = RateForm()

    return render(request, 'rate_create.html', {'create_form': create_form})


def rate_delete(request, rate_id):

    rate = get_object_or_404(Rate, id=rate_id)
    rate_form = RateForm(instance=rate)

    if request.method == 'POST':
        rate_form = RateForm(request.POST, instance=rate)

        rate.delete()
        return redirect('rate_list')
    return render(request, 'rate_delete.html', {'rate_form': rate_form})


def rate_details(request, rate_id):
    rate = get_object_or_404(Rate, id=rate_id)
    return render(request, 'rate_detail.html', {'rate': rate})


def rate_update(request, rate_id):
    rate = get_object_or_404(Rate, id=rate_id)
    if request.method == 'POST':
        rate_form = RateForm(request.POST, instance=rate)
        if rate_form.is_valid():
            rate_form.save()
            return redirect('rate_list')
    elif request.method == 'GET':
        rate_form = RateForm(instance=rate)

    return render(request, 'rate_update.html', {'rate_form': rate_form})


# Homework 8 & 9 - Class based views, Source, reverse


class SourceListView(ListView):

    model = Source
    template_name = 'show_sources.html'


class SourceCreateView(CreateView):
    model = Source
    template_name = 'source_create.html'
    form_class = SourceForm
    success_url = reverse_lazy('source_list')


class SourceDetailView(DetailView):

    queryset = Source.objects.all()
    template_name = 'source_details.html'
    context_object_name = 'detail_view'


class SourceDeleteView(DeleteView):

    queryset = Source.objects.all()
    form_class = SourceForm
    template_name = 'source_delete.html'
    success_url = reverse_lazy('source_list')
    context_object_name = 'del_view'


class SourceUpdateView(UpdateView):

    queryset = Source.objects.all()
    form_class = SourceForm
    template_name = 'source_update.html'
    success_url = reverse_lazy('source_list')
    context_object_name = 'update_view'


class ContactUsCreateView(CreateView):

    model = ContactUs
    success_url = reverse_lazy('filter_messages')
    template_name = 'contact_us_form.html'
# form = ContactUsForm - no need to mention the form,
# can copy fields from the model only (see below:)
    fields = (
        'email_from',
        'subject',
        'message',
        )

    def form_valid(self, form):
        subject = form.cleaned_data['subject']
        message = form.cleaned_data['message']
        email_from = form.cleaned_data['email_from']
        full_email_body = f'''Email from: {email_from} /n
        Body: {message}'''
        send_mail(
            subject,
            full_email_body,
            settings.EMAIL_HOST_USER,  # your from address
            ['dageneral@gmail.com'],  # list of to addresses
            fail_silently=False,
            )
        return super().form_valid(form)

# When you add the mixin, you don't need to explicitly
# call the method from that class

# the method will be executed automatically
# i.e. no need for: response_time = ResponseTimeMixin.super().rate_dispatch()

# class RateListView(ListView):
    # queryset = Rate.objects.all()
    # template_name = 'rate_detail.html'

app/currency_app/templates/ContactUsCreate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

app/currency_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
         {% block title %}
             {{ page_title|default:"Untitled Page" }}
         {% endblock title %}
    </title>

</head>
<body>

{% block nav_bar %}

    {% include 'includes/navbar.html' %}

{% endblock %}
       {% block content %}
     <p> content placeholder</p>
       {% endblock content %}
    {% block footer %}

        {% include 'includes/footer.html' %}

    {% endblock %}
</body>
</html>

app/currency_app/templates/contact_details.html
{% extends 'base.html' %}

{% block content %}



    {% include 'includes/login_div.html' %}
    <div>
        <div style="width: 50rem; margin-left: 20px; margin-top: 5px">
            <form action="{% url 'contact_us_form'  %}" method="post">
                {% csrf_token %}
                {{ contact_us_form.email_from }}
                {{ contact_us_form.subject }}
                {{ contact_us_form.message }}

            <button type="submit" class="btn btn-warning">Submit</button>
            </form>
        </div>

    </div>

 <table>
    <tr>
        <th>Email From</th>
        <th>Subject</th>
        <th>Message</th>

    </tr>
    {% for msg in msgs_filtered %}
    <tr>
        <td>{{ msg.email_from }}</td>
        <td>{{ msg.subject }}</td>
        <td>{{ msg.message }}</td>

    </tr>
    {% endfor %}
</table>


{% endblock %}

app/currency_app/templates/contact_us_form.html
{% extends 'base.html' %}

{% block content %}
<div>
<div style="width: 50rem; margin-left: 20px; margin-top: 5px">
<form action="{% url 'contact_us_form'  %}" method="post">
    {% csrf_token %}
     {{ form.as_p}}

    <button type="submit" class="btn btn-warning">Submit</button>
</form>
</div>

</div>

{% endblock %}

app/currency_app/templates/messages_filtered.html
{% extends base.html %}
<!DOCTYPE html>




<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Messages Filtered</title>
</head>
<body>

{% for msg in filter_messages %}
{% print msg %}
{% endfor %}

</body>
</html>

app/currency_app/templates/rate_delete.html
{% extends 'base.html' %}

    {% block title %}

    Are you sure you'd like to delete rate Id {{ rate_form.id }}?


    {% endblock %}

{% block content %}

    <form method="post">
    {% csrf_token %}

        {{ rate_form.as_p }}

        <button type="submit">Delete</button>
    </form>

{% endblock %}

app/currency_app/templates/rate_detail.html
{% extends 'base.html' %}

{% block title %}

Rate Detail

{% endblock %}

{% block content %}
ID:              {{ rate.id }}<br>
Currency:        {{ rate.get_currency_display }}<br>
Source:          {{ rate.source.name }}<br>
Sale:            {{ rate.sale }}<br>
Buy:             {{ rate.buy }}<br>


{% endblock %}

app/currency_app/templates/rate_page.html
{% extends 'base.html' %}
{% load static %}

{% block title %}

Rates Page

{% endblock %}

{% block content %}

    <table>
    <tr>
        <th>ID</th>
        <th>Source</th>
        <th>Currency</th>
        <th>Buy</th>
        <th>Sale</th>
        <th>Created</th>
        <th>Create</th>
        <th>Details</th>
        <th>Update </th>
        <th>Delete</th>
    </tr>
    {% for rate in rates %}
    <tr>
        <td>{{ rate.id }}</td>
        <td>{{ rate.source.name }}</td>
        <td>{{ rate.get_currency_display }}</td>
        <td>{{ rate.buy }}</td>
        <td>{{ rate.sale }}</td>
        <td> {{ rate.created }}</td>
        <td><a href='rate_create/'> Create Rate </a> </td>
        <td><a href='rate_details/{{ rate.id }}/'> Rate Details </a> </td>
        <td><a href='rate_update/{{ rate.id }}/'> Update Rate </a> </td>
        <td><a href='rate_delete/{{ rate.id }}/'> Delete Rate </a> </td>
    </tr>
    {% endfor %}
</table>


{% endblock %}

app/currency_app/templates/rate_update.html
{% extends 'base.html' %}

{% block title %}

Update Rate

{% endblock %}

{% block content %}

<form method="post">
    {% csrf_token %}
    {{ rate_form.as_p }}
    <button type="submit">Submit</button>

</form>

{% endblock %}

app/currency_app/templates/show_sources.html
{% extends 'base.html' %}

{% block content %}


 <table>
    <tr>
        <th>Source Name</th>
        <th>Source URL</th>
        <th>Create Source</th>
        <th>Update Source</th>
        <th>Source Detail</th>
        <th>Delete Source</th>


    </tr>
    {% for source in source_list %}
    <tr>
        <td>{{ source.name }}</td>
        <td>{{ source.source_url }}</td>
        <td><a href='{% url 'source_create' %}'>Create Source</a> </td>
        <td><a href='{% url 'source_update' pk=source.pk %}'>Update Source</a> </td>
        <td><a href='{% url 'source_details' pk=source.pk %}'>Source Detail</a> </td>
        <td><a href='{% url 'source_delete' pk=source.pk %}'>Delete Source</a> </td>


    </tr>
    {% endfor %}
</table>

{% endblock %}

app/currency_app/templates/source_create.html
{% extends 'base.html' %}

{% block title %}

Create Source

{% endblock %}

{% block content %}

    <h1> Create Source </h1>
    <br>

    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}
        <button type = 'Submit'>Submit</button>

    </form>



{% endblock %}

app/currency_app/templates/source_delete.html
{% extends 'base.html' %}

{% block title %}

Delete Source

{% endblock %}

{% block content %}

    Delete Source? <br>


    {{ del_view }}<br>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Submit</button>
    </form>

{% endblock %}

app/currency_app/templates/source_details.html
{% extends 'base.html' %}

{% block title %}

Source Detail

{% endblock %}

{% block content %}
ID:              {{ detail_view.id }}<br>
Source Name:        {{ detail_view.name }}<br>
Source URL:            {{ detail_view.source_url }}<br>



{% endblock %}

app/currency_app/templates/source_update.html
{% extends 'base.html' %}

{% block title %}

Update Source

{% endblock %}

{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>


</form>

{% endblock %}